### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by StanGirard** [padok-team/terraform-azurerm-storage-account-website#1]
- [ ]  It works in production
- [ ]  It allows data backup (if needed)
- [ ]  It allows rotation of secrets
- [ ]  It allows to store secrets in Key Vault
- [ ]  It encrypts data by default with Azure key or with user provided keys
- [ ]  It allows outputing of logs in other solutions
- [X]  It allows replication and high availability
- [ ]  It allows integration in VNET (Needs to figure out how to manager private endpoint)
- [ ]  It allows control on network flows
